In [1]:
# import some important library 
import pandas as pd

In [2]:
#    Dataset is available as csv file (now we are providing file path)    #
data=pd.read_csv(r'C:\Users\Micro\Downloads\weather3.csv')

In [3]:
data

,Precipitation,Date,Month,Week,Year,City,Code,Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
0,0.00,1/3/2016,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.00,1/3/2016,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86
2,0.16,1/3/2016,1,3,2016,Mobile,MOB,"Mobile, AL",Alabama,46,51,41,35,9.73
3,0.00,1/3/2016,1,3,2016,Montgomery,MGM,"Montgomery, AL",Alabama,45,52,38,32,6.86
4,0.01,1/3/2016,1,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,34,38,29,19,7.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16738,0.08,1/1/2017,1,1,2017,Casper,CPR,"Casper, WY",Wyoming,23,32,15,23,19.98
16739,0.00,1/1/2017,1,1,2017,Cheyenne,CYS,"Cheyenne, WY",Wyoming,32,42,21,26,15.16
16740,0.00,1/1/2017,1,1,2017,Lander,LND,"Lander, WY",Wyoming,17,29,4,26,1.65
16741,0.06,1/1/2017,1,1,2017,Rawlins,RWL,"Rawlins, WY",Wyoming,23,31,13,24,18.16
16742,0.10,1/1/2017,1,1,2017,Sheridan,SHR,"Sheridan, WY",Wyoming,21,34,8,23,7.51

#  .head ()
 It shows N number of row in data(by defalult,N=5)

In [4]:
data.head(10)

,Precipitation,Date,Month,Week,Year,City,Code,Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
0,0.00,1/3/2016,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.00,1/3/2016,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86
2,0.16,1/3/2016,1,3,2016,Mobile,MOB,"Mobile, AL",Alabama,46,51,41,35,9.73
3,0.00,1/3/2016,1,3,2016,Montgomery,MGM,"Montgomery, AL",Alabama,45,52,38,32,6.86
4,0.01,1/3/2016,1,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,34,38,29,19,7.80
5,0.09,1/3/2016,1,3,2016,Annette,ANN,"Annette, AK",Alaska,38,44,31,9,8.70
6,0.05,1/3/2016,1,3,2016,Bethel,BET,"Bethel, AK",Alaska,30,36,24,9,16.46
7,0.15,1/3/2016,1,3,2016,Bettles,BTT,"Bettles, AK",Alaska,22,32,9,2,3.10
8,0.60,1/3/2016,1,3,2016,Cold Bay,CDB,"Cold Bay, AK",Alaska,34,36,31,20,9.10
9,2.15,1/3/2016,1,3,2016,Cordova,CDV,"Cordova, AK",Alaska,38,43,33,9,9.76

#  .shape
It shows number of rows and number of column in dataframe

In [5]:
data.shape

(16743, 14)

# .index
This attribute provides index of dataframe

In [6]:
data.index

RangeIndex(start=0, stop=16743, step=1)

# .dtypes
it describes data type of each column

In [7]:
data.dtypes

Precipitation       float64
Date                 object
Month                 int64
Week                  int64
Year                  int64
City                 object
Code                 object
Location             object
State                object
Temperature_Avg       int64
Temperature_Max       int64
Temperature_Min       int64
Wind_Direction        int64
Wind_Speed          float64
dtype: object

#  .unique
In a column,it shows all unique values,applied on a single column only.

In [9]:
data['Location'].unique()

array(['Birmingham, AL', 'Huntsville, AL', 'Mobile, AL', 'Montgomery, AL',
       'Anchorage, AK', 'Annette, AK', 'Bethel, AK', 'Bettles, AK',
       'Cold Bay, AK', 'Cordova, AK', 'Delta Junction/Ft Greely, AK',
       'Fairbanks, AK', 'Gulkana, AK', 'Homer, AK', 'Iliamna, AK',
       'Juneau, AK', 'Kenai, AK', 'Ketchikan, AK', 'King Salmon, AK',
       'Kodiak, AK', 'Kotzebue, AK', 'Mc Grath, AK', 'Nome, AK',
       'Northway, AK', 'Palmer, AK', 'Petersburg, AK',
       'Puntilla Lake, AK', 'Shemya, AK', 'Sitka, AK', 'Skagway, AK',
       'St Paul Island, AK', 'Talkeetna, AK', 'Tanana, AK',
       'Utqiagvik (Barrow), AK', 'Yakutat, AK', 'Douglas Bisbee, AZ',
       'Kingman, AZ', 'Phoenix, AZ', 'Tucson, AZ', 'Winslow, AZ',
       'Fort Smith, AR', 'Harrison, AR', 'North Little Rock, AR',
       'Bakersfield, CA', 'Bishop, CA', 'China Lake, CA', 'Concord, CA',
       'Eureka, CA', 'Fresno, CA', 'Hayward, CA', 'Long Beach, CA',
       'Los Angeles, CA', 'Red Bluff, CA', 'Redding, CA',
       'Sacramento, CA', 'Salinas, CA', 'San Diego, CA',
       'San Francisco, CA', 'Sandberg, CA', 'Santa Barbara, CA',
       'Santa Maria, CA', 'Stockton, CA', 'Alamosa, CO',
       'Colorado Springs, CO', 'Craig, CO', 'Denver, CO',
       'Grand Junction, CO', 'Pueblo, CO', 'Bridgeport, CT',
       'Windsor Locks, CT', 'Newark, DE', 'Wilmington, DE',
       'Daytona Beach, FL', 'Fort Lauderdale, FL', 'Gainesville, FL',
       'Jacksonville, FL', 'Key West, FL', 'Miami, FL', 'Orlando, FL',
       'Pensacola, FL', 'Tallahassee, FL', 'Tampa, FL', 'Vero Beach, FL',
       'West Palm Beach, FL', 'Alma, GA', 'Athens, GA', 'Atlanta, GA',
       'Augusta, GA', 'Macon, GA', 'Savannah, GA', 'Hilo, HI',
       'Honolulu, HI', 'Kahului, HI', 'Kaunakakai, HI', 'Lihue, HI',
       'Boise, ID', 'Lewiston, ID', 'Pocatello, ID', 'Chicago, IL',
       'Moline, IL', 'Peoria, IL', 'Quincy, IL', 'Rockford, IL',
       'Springfield, IL', 'Evansville, IN', 'Fort Wayne, IN',
       'Indianapolis, IN', 'South Bend, IN', 'Cedar Rapids, IA',
       'Des Moines, IA', 'Dubuque, IA', 'Sioux City, IA', 'Waterloo, IA',
       'Concordia, KS', 'Dodge City, KS', 'Goodland, KS',
       'Medicine Lodge, KS', 'Topeka, KS', 'Wichita, KS', 'Covington, KY',
       'Jackson, KY', 'Lexington, KY', 'Louisville, KY', 'Paducah, KY',
       'Baton Rouge, LA', 'Lake Charles, LA', 'New Orleans, LA',
       'Shreveport, LA', 'Slidell, LA', 'Bangor, ME', 'Caribou, ME',
       'Portland, ME', 'Baltimore, MD', 'Salisbury, MD', 'Boston, MA',
       'Milton, MA', 'Worcester, MA', 'Alpena, MI', 'Detroit, MI',
       'Flint, MI', 'Grand Rapids, MI', 'Houghton Lake, MI',
       'Lansing, MI', 'Marquette, MI', 'Muskegon, MI',
       'Sault Ste Marie, MI', 'Duluth, MN', 'International Falls, MN',
       'Minneapolis, MN', 'Rochester, MN', 'St Cloud, MN',
       'Greenville, MS', 'Greenwood, MS', 'Gulfport, MS',
       'Hattiesburg, MS', 'Jackson, MS', 'Meridian, MS', 'Tupelo, MS',
       'Cape Girardeau, MO', 'Columbia, MO', 'Kansas City, MO',
       'Rolla/Vichy, MO', 'Springfield, MO', 'St Joseph, MO',
       'St Louis, MO', 'Billings, MT', 'Butte, MT', 'Cut Bank, MT',
       'Dillon, MT', 'Glasgow, MT', 'Great Falls, MT', 'Havre, MT',
       'Helena, MT', 'Kalispell, MT', 'Miles City, MT', 'Missoula, MT',
       'Grand Island, NE', 'Lincoln, NE', 'Norfolk, NE',
       'North Platte, NE', 'Omaha, NE', 'Scottsbluff, NE', 'Sidney, NE',
       'Valentine, NE', 'Ely, NV', 'Eureka, NV', 'Las Vegas, NV',
       'Mercury, NV', 'Reno, NV', 'Winnemucca, NV', 'Concord, NH',
       'Mt. Washington, NH', 'Atlantic City, NJ', 'Newark, NJ',
       'Albuquerque, NM', 'Clayton, NM', 'Roswell, NM', 'Albany, NY',
       'Binghamton, NY', 'Buffalo, NY', 'Glens Falls, NY', 'Islip, NY',
       'New York, NY', 'Rochester, NY', 'Syracuse, NY', 'Asheville, NC',
       'Cape Hatteras, NC', 'Charlotte, NC', 'Greensboro, NC',
       'Hickory, NC', 'Raleigh/Durham, NC', 'Wilmington, NC',
       'Bismarck, ND', 'Dickinson, ND', 'Fargo, ND', 'Grand Forks, ND',
       'Williston, ND', 'Akron, OH', 'Cleveland, OH', 'Columbus, OH',
       'Dayton, OH', 'Mansfield, OH', 'Toledo, OH',
       'Youngstown/Warren, OH', 'Gage, OK', 'Oklahoma City, OK',
       'Ponca City, OK', 'Tulsa, OK', 'Astoria, OR', 'Burns, OR',
       'Eugene, OR', 'Medford, OR', 'Pendleton, OR', 'Portland, OR',
       'Redmond, OR', 'Salem, OR', 'Allentown, PA', 'Erie, PA',
       'Harrisburg, PA', 'Philadelphia, PA', 'Pittsburgh, PA',
       'Wilkes-Barre/Scranton, PA', 'Williamsport, PA', 'San Juan, PR',
       'Providence, RI', 'Anderson, SC', 'Charleston, SC', 'Columbia, SC',
       'Greer, SC', 'Aberdeen, SD', 'Huron, SD', 'Pierre, SD',
       'Rapid City, SD', 'Sioux Falls, SD',
       'Bristol/Jhnsn Cty/Kngsprt, TN', 'Chattanooga, TN',
       'Clarksville, TN', 'Crossville, TN', 'Knoxville, TN',
       'Memphis, TN', 'Nashville, TN', 'Oak Ridge, TN', 'Abilene, TX',
       'Amarillo, TX', 'Austin/Bergstrom, TX', 'Austin/City, TX',
       'Beaumont/Port Arthur, TX', 'Brownsville, TX', 'Childress, TX',
       'College Station, TX', 'Corpus Christi, TX', 'Dalhart, TX',
       'Dallas, TX', 'Dallas-Fort Worth, TX', 'Del Rio, TX',
       'El Paso, TX', 'Fort Worth, TX', 'Galveston, TX', 'Houston, TX',
       'Lubbock, TX', 'Midland, TX', 'San Angelo, TX', 'San Antonio, TX',
       'Victoria, TX', 'Waco, TX', 'Wichita Falls, TX',
       'Salt Lake City, UT', 'Blacksburg, VA', 'Burlington, VT',
       'Lynchburg, VA', 'Norfolk, VA', 'Richmond, VA', 'Roanoke, VA',
       'Wallops Island, VA', 'Washington, VA', 'Deer Park, WA',
       'Ephrata, WA', 'Olympia, WA', 'Quillayute, WA', 'Seattle, WA',
       'Spokane, WA', 'Yakima, WA', 'Beckley, WV', 'Charleston, WV',
       'Elkins, WV', 'Huntington, WV', 'Green Bay, WI', 'La Crosse, WI',
       'Madison, WI', 'Milwaukee, WI', 'Casper, WY', 'Cheyenne, WY',
       'Lander, WY', 'Rawlins, WY', 'Sheridan, WY', 'Gustavus, AK',
       'Wrangell, AK', 'Unalakleet, AK'], dtype=object)

#  .nunique
It shows the total number of unique values in each column,it can applied on both single column and dataframe.

In [10]:
data.nunique()

Precipitation        565
Date                  53
Month                 12
Week                  31
Year                   2
City                 307
Code                 318
Location             318
State                 53
Temperature_Avg      119
Temperature_Max      125
Temperature_Min      114
Wind_Direction        37
Wind_Speed          1461
dtype: int64

# .count
It shows total number of non-null in each column.It can be applied on a single column as well as on whole dataframe.

In [11]:
data.count()

Precipitation       16743
Date                16743
Month               16743
Week                16743
Year                16743
City                16743
Code                16743
Location            16743
State               16743
Temperature_Avg     16743
Temperature_Max     16743
Temperature_Min     16743
Wind_Direction      16743
Wind_Speed          16743
dtype: int64

# .value_counts
in a column,it shows all unique values with their count but applied only on single column.

In [13]:
data['State'].value_counts()

Alaska            1719
Texas             1272
California         999
Florida            636
Montana            583
Michigan           477
Nebraska           424
New York           424
Oregon             424
Tennessee          420
Pennsylvania       371
Mississippi        371
Ohio               371
North Carolina     371
Washington         371
Missouri           371
Georgia            318
Illinois           318
Kansas             318
Nevada             318
Colorado           318
Virginia           318
South Dakota       265
North Dakota       265
Wyoming            265
Minnesota          265
Arizona            265
Hawaii             265
Kentucky           265
Iowa               265
Louisiana          261
Oklahoma           212
Wisconsin          212
West Virginia      212
South Carolina     212
Alabama            212
Indiana            212
Idaho              159
New Mexico         159
Maine              159
Arkansas           159
Massachusetts      153
Maryland           106
Connecticut        106
New Jersey         106
New Hampshire      100
DE                  53
Utah                53
VA                  53
Vermont             53
Delaware            53
Rhode Island        53
Puerto Rico         53
Name: State, dtype: int64

# .info
provides basic information about dataframe.

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16743 entries, 0 to 16742
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Precipitation     16743 non-null  float64
 1   Date              16743 non-null  object
 2   Month             16743 non-null  int64
 3   Week              16743 non-null  int64
 4   Year              16743 non-null  int64
 5   City              16743 non-null  object
 6   Code              16743 non-null  object
 7   Location          16743 non-null  object
 8   State             16743 non-null  object
 9   Temperature_Avg   16743 non-null  int64
 10  Temperature_Max   16743 non-null  int64
 11  Temperature_Min   16743 non-null  int64
 12  Wind_Direction    16743 non-null  int64
 13  Wind_Speed        16743 non-null  float64
dtypes: float64(2), int64(7), object(5)
memory usage: 1.8+ MB

# Q.1) Find all the unique "wind speed" values in data?

In [16]:
data.head(5)

,Precipitation,Date,Month,Week,Year,City,Code,Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
0,0.00,1/3/2016,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.00,1/3/2016,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86
2,0.16,1/3/2016,1,3,2016,Mobile,MOB,"Mobile, AL",Alabama,46,51,41,35,9.73
3,0.00,1/3/2016,1,3,2016,Montgomery,MGM,"Montgomery, AL",Alabama,45,52,38,32,6.86
4,0.01,1/3/2016,1,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,34,38,29,19,7.80

In [17]:
data.nunique()

Precipitation        565
Date                  53
Month                 12
Week                  31
Year                   2
City                 307
Code                 318
Location             318
State                 53
Temperature_Avg      119
Temperature_Max      125
Temperature_Min      114
Wind_Direction        37
Wind_Speed          1461
dtype: int64

In [24]:
data['Wind_Speed'].nunique()

1461

In [28]:
data['Wind_Speed'].unique()

array([ 4.33,  3.86,  9.73, ..., 12.53, 19.98, 18.16])

#  Q.2)  Find the number of times when the location is "Anchorage, AK"	?

In [29]:
data.head(5)

,Precipitation,Date,Month,Week,Year,City,Code,Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
0,0.00,1/3/2016,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.00,1/3/2016,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86
2,0.16,1/3/2016,1,3,2016,Mobile,MOB,"Mobile, AL",Alabama,46,51,41,35,9.73
3,0.00,1/3/2016,1,3,2016,Montgomery,MGM,"Montgomery, AL",Alabama,45,52,38,32,6.86
4,0.01,1/3/2016,1,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,34,38,29,19,7.80

In [31]:
#value_counts
data['City'].value_counts()

Norfolk           106
Jackson           106
Springfield       106
Charleston        106
Newark            106
                 ...
Milton             47
Mt. Washington     47
China Lake         45
Wrangell           30
Unalakleet          5
Name: City, Length: 307, dtype: int64

In [39]:
#filtering data
#data.head(3)
data[data.Location == 'Anchorage, AK']

,Precipitation,Date,Month,Week,Year,City,Code,Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
4,0.01,1/3/2016,1,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,34,38,29,19,7.80
319,0.00,1/10/2016,1,10,2016,Anchorage,ANC,"Anchorage, AK",Alaska,28,33,22,12,4.02
634,0.15,1/17/2016,1,17,2016,Anchorage,ANC,"Anchorage, AK",Alaska,24,28,19,7,3.78
949,0.00,1/24/2016,1,24,2016,Anchorage,ANC,"Anchorage, AK",Alaska,23,28,19,6,3.64
1264,0.12,1/31/2016,1,31,2016,Anchorage,ANC,"Anchorage, AK",Alaska,30,35,25,20,2.70
1579,0.08,2/7/2016,2,7,2016,Anchorage,ANC,"Anchorage, AK",Alaska,26,31,20,5,3.97
1894,0.01,2/14/2016,2,14,2016,Anchorage,ANC,"Anchorage, AK",Alaska,30,35,25,17,2.88
2209,0.23,2/21/2016,2,21,2016,Anchorage,ANC,"Anchorage, AK",Alaska,25,32,19,22,3.85
2524,0.00,2/28/2016,2,28,2016,Anchorage,ANC,"Anchorage, AK",Alaska,36,42,30,20,4.85
2839,0.04,3/6/2016,3,6,2016,Anchorage,ANC,"Anchorage, AK",Alaska,30,36,22,20,3.61
3156,0.00,3/13/2016,3,13,2016,Anchorage,ANC,"Anchorage, AK",Alaska,33,41,25,16,2.20
3471,0.61,3/20/2016,3,20,2016,Anchorage,ANC,"Anchorage, AK",Alaska,28,34,21,16,4.17
3786,0.16,3/27/2016,3,27,2016,Anchorage,ANC,"Anchorage, AK",Alaska,38,46,31,13,2.71
4101,0.00,4/3/2016,4,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,41,48,35,22,8.40
4418,0.00,4/10/2016,4,10,2016,Anchorage,ANC,"Anchorage, AK",Alaska,41,49,33,18,4.61
4734,0.02,4/17/2016,4,17,2016,Anchorage,ANC,"Anchorage, AK",Alaska,43,52,33,21,4.37
5050,0.00,4/24/2016,4,24,2016,Anchorage,ANC,"Anchorage, AK",Alaska,45,54,33,15,5.04
5366,0.00,5/1/2016,5,1,2016,Anchorage,ANC,"Anchorage, AK",Alaska,44,49,39,16,5.70
5683,0.08,5/8/2016,5,8,2016,Anchorage,ANC,"Anchorage, AK",Alaska,45,52,38,17,5.91
6000,0.10,5/15/2016,5,15,2016,Anchorage,ANC,"Anchorage, AK",Alaska,55,64,45,19,4.00
6317,0.11,5/22/2016,5,22,2016,Anchorage,ANC,"Anchorage, AK",Alaska,51,57,45,18,5.52
6634,0.01,5/29/2016,5,29,2016,Anchorage,ANC,"Anchorage, AK",Alaska,56,66,46,23,3.98
6951,0.00,6/5/2016,6,5,2016,Anchorage,ANC,"Anchorage, AK",Alaska,57,63,49,18,7.84
7268,1.10,6/12/2016,6,12,2016,Anchorage,ANC,"Anchorage, AK",Alaska,55,62,47,22,4.51
7583,0.09,6/19/2016,6,19,2016,Anchorage,ANC,"Anchorage, AK",Alaska,61,70,52,23,6.32
7898,0.46,6/26/2016,6,26,2016,Anchorage,ANC,"Anchorage, AK",Alaska,60,67,53,20,4.62
8213,0.35,7/3/2016,7,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,59,63,55,23,2.80
8529,0.34,7/10/2016,7,10,2016,Anchorage,ANC,"Anchorage, AK",Alaska,62,68,55,22,3.61
8843,0.00,7/17/2016,7,17,2016,Anchorage,ANC,"Anchorage, AK",Alaska,64,72,55,28,3.22
9157,1.36,7/24/2016,7,24,2016,Anchorage,ANC,"Anchorage, AK",Alaska,65,71,58,23,3.92
9471,0.43,7/31/2016,7,31,2016,Anchorage,ANC,"Anchorage, AK",Alaska,61,66,56,15,6.15
9785,1.88,8/7/2016,8,7,2016,Anchorage,ANC,"Anchorage, AK",Alaska,61,66,55,19,2.12
10102,1.78,8/14/2016,8,14,2016,Anchorage,ANC,"Anchorage, AK",Alaska,60,64,55,13,3.47
10419,0.19,8/21/2016,8,21,2016,Anchorage,ANC,"Anchorage, AK",Alaska,60,66,54,17,4.62
10736,1.60,8/28/2016,8,28,2016,Anchorage,ANC,"Anchorage, AK",Alaska,61,68,54,14,2.77
11053,0.12,9/4/2016,9,4,2016,Anchorage,ANC,"Anchorage, AK",Alaska,58,67,48,16,2.20
11370,0.86,9/11/2016,9,11,2016,Anchorage,ANC,"Anchorage, AK",Alaska,54,60,48,15,5.80
11686,0.60,9/18/2016,9,18,2016,Anchorage,ANC,"Anchorage, AK",Alaska,52,58,46,13,5.07
12002,0.77,9/25/2016,9,25,2016,Anchorage,ANC,"Anchorage, AK",Alaska,50,55,44,13,8.80
12318,0.13,10/2/2016,10,2,2016,Anchorage,ANC,"Anchorage, AK",Alaska,44,51,37,22,2.85
12635,0.00,10/9/2016,10,9,2016,Anchorage,ANC,"Anchorage, AK",Alaska,41,49,31,12,1.60
12952,0.00,10/16/2016,10,16,2016,Anchorage,ANC,"Anchorage, AK",Alaska,37,46,29,11,3.84
13269,0.31,10/23/2016,10,23,2016,Anchorage,ANC,"Anchorage, AK",Alaska,33,38,26,23,5.77
13586,0.15,10/30/2016,10,30,2016,Anchorage,ANC,"Anchorage, AK",Alaska,30,36,23,13,2.20
13903,0.08,11/6/2016,11,6,2016,Anchorage,ANC,"Anchorage, AK",Alaska,31,38,26,10,3.15
14220,0.06,11/13/2016,11,13,2016,Anchorage,ANC,"Anchorage, AK",Alaska,35,40,29,13,3.38
14534,0.07,11/20/2016,11,20,2016,Anchorage,ANC,"Anchorage, AK",Alaska,25,29,21,19,5.58
14848,0.03,11/27/2016,11,27,2016,Anchorage,ANC,"Anchorage, AK",Alaska,19,24,14,3,3.92
15162,0.50,12/4/2016,12,4,2016,Anchorage,ANC,"Anchorage, AK",Alaska,15,19,10,18,9.25
15479,0.03,12/11/2016,12,11,2016,Anchorage,ANC,"Anchorage, AK",Alaska,12,18,6,15,6.65
15796,0.33,12/18/2016,12,18,2016,Anchorage,ANC,"Anchorage, AK",Alaska,17,22,10,15,3.90
16113,0.09,12/25/2016,12,25,2016,Anchorage,ANC,"Anchorage, AK",Alaska,16,22,11,10,2.58
16430,0.52,1/1/2017,1,1,2017,Anchorage,ANC,"Anchorage, AK",Alaska,20,27,12,7,2.45

In [41]:
#groupby()
#data.head(2)
data.groupby('Location').get_group('Anchorage, AK')

,Precipitation,Date,Month,Week,Year,City,Code,Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
4,0.01,1/3/2016,1,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,34,38,29,19,7.80
319,0.00,1/10/2016,1,10,2016,Anchorage,ANC,"Anchorage, AK",Alaska,28,33,22,12,4.02
634,0.15,1/17/2016,1,17,2016,Anchorage,ANC,"Anchorage, AK",Alaska,24,28,19,7,3.78
949,0.00,1/24/2016,1,24,2016,Anchorage,ANC,"Anchorage, AK",Alaska,23,28,19,6,3.64
1264,0.12,1/31/2016,1,31,2016,Anchorage,ANC,"Anchorage, AK",Alaska,30,35,25,20,2.70
1579,0.08,2/7/2016,2,7,2016,Anchorage,ANC,"Anchorage, AK",Alaska,26,31,20,5,3.97
1894,0.01,2/14/2016,2,14,2016,Anchorage,ANC,"Anchorage, AK",Alaska,30,35,25,17,2.88
2209,0.23,2/21/2016,2,21,2016,Anchorage,ANC,"Anchorage, AK",Alaska,25,32,19,22,3.85
2524,0.00,2/28/2016,2,28,2016,Anchorage,ANC,"Anchorage, AK",Alaska,36,42,30,20,4.85
2839,0.04,3/6/2016,3,6,2016,Anchorage,ANC,"Anchorage, AK",Alaska,30,36,22,20,3.61
3156,0.00,3/13/2016,3,13,2016,Anchorage,ANC,"Anchorage, AK",Alaska,33,41,25,16,2.20
3471,0.61,3/20/2016,3,20,2016,Anchorage,ANC,"Anchorage, AK",Alaska,28,34,21,16,4.17
3786,0.16,3/27/2016,3,27,2016,Anchorage,ANC,"Anchorage, AK",Alaska,38,46,31,13,2.71
4101,0.00,4/3/2016,4,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,41,48,35,22,8.40
4418,0.00,4/10/2016,4,10,2016,Anchorage,ANC,"Anchorage, AK",Alaska,41,49,33,18,4.61
4734,0.02,4/17/2016,4,17,2016,Anchorage,ANC,"Anchorage, AK",Alaska,43,52,33,21,4.37
5050,0.00,4/24/2016,4,24,2016,Anchorage,ANC,"Anchorage, AK",Alaska,45,54,33,15,5.04
5366,0.00,5/1/2016,5,1,2016,Anchorage,ANC,"Anchorage, AK",Alaska,44,49,39,16,5.70
5683,0.08,5/8/2016,5,8,2016,Anchorage,ANC,"Anchorage, AK",Alaska,45,52,38,17,5.91
6000,0.10,5/15/2016,5,15,2016,Anchorage,ANC,"Anchorage, AK",Alaska,55,64,45,19,4.00
6317,0.11,5/22/2016,5,22,2016,Anchorage,ANC,"Anchorage, AK",Alaska,51,57,45,18,5.52
6634,0.01,5/29/2016,5,29,2016,Anchorage,ANC,"Anchorage, AK",Alaska,56,66,46,23,3.98
6951,0.00,6/5/2016,6,5,2016,Anchorage,ANC,"Anchorage, AK",Alaska,57,63,49,18,7.84
7268,1.10,6/12/2016,6,12,2016,Anchorage,ANC,"Anchorage, AK",Alaska,55,62,47,22,4.51
7583,0.09,6/19/2016,6,19,2016,Anchorage,ANC,"Anchorage, AK",Alaska,61,70,52,23,6.32
7898,0.46,6/26/2016,6,26,2016,Anchorage,ANC,"Anchorage, AK",Alaska,60,67,53,20,4.62
8213,0.35,7/3/2016,7,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,59,63,55,23,2.80
8529,0.34,7/10/2016,7,10,2016,Anchorage,ANC,"Anchorage, AK",Alaska,62,68,55,22,3.61
8843,0.00,7/17/2016,7,17,2016,Anchorage,ANC,"Anchorage, AK",Alaska,64,72,55,28,3.22
9157,1.36,7/24/2016,7,24,2016,Anchorage,ANC,"Anchorage, AK",Alaska,65,71,58,23,3.92
9471,0.43,7/31/2016,7,31,2016,Anchorage,ANC,"Anchorage, AK",Alaska,61,66,56,15,6.15
9785,1.88,8/7/2016,8,7,2016,Anchorage,ANC,"Anchorage, AK",Alaska,61,66,55,19,2.12
10102,1.78,8/14/2016,8,14,2016,Anchorage,ANC,"Anchorage, AK",Alaska,60,64,55,13,3.47
10419,0.19,8/21/2016,8,21,2016,Anchorage,ANC,"Anchorage, AK",Alaska,60,66,54,17,4.62
10736,1.60,8/28/2016,8,28,2016,Anchorage,ANC,"Anchorage, AK",Alaska,61,68,54,14,2.77
11053,0.12,9/4/2016,9,4,2016,Anchorage,ANC,"Anchorage, AK",Alaska,58,67,48,16,2.20
11370,0.86,9/11/2016,9,11,2016,Anchorage,ANC,"Anchorage, AK",Alaska,54,60,48,15,5.80
11686,0.60,9/18/2016,9,18,2016,Anchorage,ANC,"Anchorage, AK",Alaska,52,58,46,13,5.07
12002,0.77,9/25/2016,9,25,2016,Anchorage,ANC,"Anchorage, AK",Alaska,50,55,44,13,8.80
12318,0.13,10/2/2016,10,2,2016,Anchorage,ANC,"Anchorage, AK",Alaska,44,51,37,22,2.85
12635,0.00,10/9/2016,10,9,2016,Anchorage,ANC,"Anchorage, AK",Alaska,41,49,31,12,1.60
12952,0.00,10/16/2016,10,16,2016,Anchorage,ANC,"Anchorage, AK",Alaska,37,46,29,11,3.84
13269,0.31,10/23/2016,10,23,2016,Anchorage,ANC,"Anchorage, AK",Alaska,33,38,26,23,5.77
13586,0.15,10/30/2016,10,30,2016,Anchorage,ANC,"Anchorage, AK",Alaska,30,36,23,13,2.20
13903,0.08,11/6/2016,11,6,2016,Anchorage,ANC,"Anchorage, AK",Alaska,31,38,26,10,3.15
14220,0.06,11/13/2016,11,13,2016,Anchorage,ANC,"Anchorage, AK",Alaska,35,40,29,13,3.38
14534,0.07,11/20/2016,11,20,2016,Anchorage,ANC,"Anchorage, AK",Alaska,25,29,21,19,5.58
14848,0.03,11/27/2016,11,27,2016,Anchorage,ANC,"Anchorage, AK",Alaska,19,24,14,3,3.92
15162,0.50,12/4/2016,12,4,2016,Anchorage,ANC,"Anchorage, AK",Alaska,15,19,10,18,9.25
15479,0.03,12/11/2016,12,11,2016,Anchorage,ANC,"Anchorage, AK",Alaska,12,18,6,15,6.65
15796,0.33,12/18/2016,12,18,2016,Anchorage,ANC,"Anchorage, AK",Alaska,17,22,10,15,3.90
16113,0.09,12/25/2016,12,25,2016,Anchorage,ANC,"Anchorage, AK",Alaska,16,22,11,10,2.58
16430,0.52,1/1/2017,1,1,2017,Anchorage,ANC,"Anchorage, AK",Alaska,20,27,12,7,2.45

# Q.3) Find the number of times when the 'wind speed was exactly 4km/h'.

In [42]:
data.head(2)

,Precipitation,Date,Month,Week,Year,City,Code,Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
0,0.0,1/3/2016,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.0,1/3/2016,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86

In [43]:
data[data['Wind_Speed'] == 4 ]

,Precipitation,Date,Month,Week,Year,City,Code,Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
232,0.01,1/3/2016,1,3,2016,Pendleton,PDT,"Pendleton, OR",Oregon,19,20,17,12,4.0
531,0.05,1/10/2016,1,10,2016,Williston,ISN,"Williston, ND",North Dakota,10,20,3,21,4.0
1155,0.96,1/24/2016,1,24,2016,Raleigh/Durham,RDU,"Raleigh/Durham, NC",North Carolina,30,37,23,23,4.0
2572,0.06,2/28/2016,2,28,2016,Red Bluff,RBL,"Red Bluff, CA",California,56,68,43,31,4.0
2648,1.68,2/28/2016,2,28,2016,Slidell,ASD,"Slidell, LA",Louisiana,55,67,43,17,4.0
4331,0.00,4/3/2016,4,3,2016,Pendleton,PDT,"Pendleton, OR",Oregon,58,73,42,17,4.0
5307,0.22,4/24/2016,4,24,2016,Nashville,BNA,"Nashville, TN",Tennessee,67,80,53,24,4.0
5515,0.00,5/1/2016,5,1,2016,Greenville,GLH,"Greenville, MS",Mississippi,75,84,66,14,4.0
6000,0.10,5/15/2016,5,15,2016,Anchorage,ANC,"Anchorage, AK",Alaska,55,64,45,19,4.0
6297,0.04,5/15/2016,5,15,2016,Seattle,SEA,"Seattle, WA",Washington,60,70,49,20,4.0
6335,0.56,5/22/2016,5,22,2016,Mc Grath,MCG,"Mc Grath, AK",Alaska,47,55,39,17,4.0
6820,0.02,5/29/2016,5,29,2016,Reno,RNO,"Reno, NV",Nevada,60,74,46,28,4.0
6885,2.17,5/29/2016,5,29,2016,Sioux Falls,FSD,"Sioux Falls, SD",South Dakota,67,77,57,14,4.0
6897,1.08,5/29/2016,5,29,2016,Austin/City,ATT,"Austin/City, TX",Texas,78,86,70,14,4.0
7880,0.14,6/19/2016,6,19,2016,Yakima,YKM,"Yakima, WA",Washington,58,73,42,26,4.0
8630,3.33,7/10/2016,7,10,2016,Evansville,EVV,"Evansville, IN",Indiana,78,86,70,21,4.0
9338,0.00,7/24/2016,7,24,2016,Eureka,P68,"Eureka, NV",Nevada,70,94,46,20,4.0
10150,0.00,8/14/2016,8,14,2016,Long Beach,LGB,"Long Beach, CA",California,74,82,66,26,4.0
11248,0.00,9/4/2016,9,4,2016,Albany,ALB,"Albany, NY",New York,67,78,56,27,4.0
11255,0.00,9/4/2016,9,4,2016,Syracuse,SYR,"Syracuse, NY",New York,65,76,53,26,4.0
12458,0.24,10/2/2016,10,2,2016,Lansing,LAN,"Lansing, MI",Michigan,59,68,50,18,4.0
12460,0.31,10/2/2016,10,2,2016,Muskegon,MKG,"Muskegon, MI",Michigan,61,69,53,19,4.0
12512,0.00,10/2/2016,10,2,2016,Roswell,ROW,"Roswell, NM",New Mexico,69,86,52,19,4.0
12684,0.00,10/9/2016,10,9,2016,Los Angeles,LAX,"Los Angeles, CA",California,69,78,60,25,4.0
13140,0.03,10/16/2016,10,16,2016,Concord,CON,"Concord, NH",New Hampshire,49,64,33,21,4.0
13311,0.00,10/23/2016,10,23,2016,Bishop,BIH,"Bishop, CA",California,58,78,38,27,4.0
13710,0.00,10/30/2016,10,30,2016,New Orleans,MSY,"New Orleans, LA",Louisiana,74,84,64,6,4.0
14411,0.00,11/13/2016,11,13,2016,Roswell,ROW,"Roswell, NM",New Mexico,54,67,40,22,4.0
14694,0.38,11/20/2016,11,20,2016,Billings,BIL,"Billings, MT",Montana,38,46,31,16,4.0
14827,3.17,11/20/2016,11,20,2016,Quillayute,UIL,"Quillayute, WA",Washington,46,52,39,12,4.0
14967,0.60,11/27/2016,11,27,2016,Paducah,PAH,"Paducah, KY",Kentucky,44,53,34,13,4.0
15458,2.84,12/4/2016,12,4,2016,Quillayute,UIL,"Quillayute, WA",Washington,43,48,38,21,4.0
16478,0.50,1/1/2017,1,1,2017,Long Beach,LGB,"Long Beach, CA",California,59,69,48,25,4.0

#  Q.4)  Find out all the null values in the data?

In [48]:
data.isnull().sum()

Precipitation       0
Date                0
Month               0
Week                0
Year                0
City                0
Code                0
Location            0
State               0
Temperature_Avg     0
Temperature_Max     0
Temperature_Min     0
Wind_Direction      0
Wind_Speed          0
dtype: int64

#  Q.5) Rename the column name "location" of the dataframe to "station_location".

In [51]:
# data.rename
data.rename(columns={'Location' : 'Station_Location'},inplace= True)

In [52]:
data.head()

,Precipitation,Date,Month,Week,Year,City,Code,Station_Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
0,0.00,1/3/2016,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.00,1/3/2016,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86
2,0.16,1/3/2016,1,3,2016,Mobile,MOB,"Mobile, AL",Alabama,46,51,41,35,9.73
3,0.00,1/3/2016,1,3,2016,Montgomery,MGM,"Montgomery, AL",Alabama,45,52,38,32,6.86
4,0.01,1/3/2016,1,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,34,38,29,19,7.80

# Q.6) What is the mean "Temperature_Min" ?

In [55]:
data.head(50)

,Precipitation,Date,Month,Week,Year,City,Code,Station_Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
0,0.00,1/3/2016,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.00,1/3/2016,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86
2,0.16,1/3/2016,1,3,2016,Mobile,MOB,"Mobile, AL",Alabama,46,51,41,35,9.73
3,0.00,1/3/2016,1,3,2016,Montgomery,MGM,"Montgomery, AL",Alabama,45,52,38,32,6.86
4,0.01,1/3/2016,1,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,34,38,29,19,7.80
5,0.09,1/3/2016,1,3,2016,Annette,ANN,"Annette, AK",Alaska,38,44,31,9,8.70
6,0.05,1/3/2016,1,3,2016,Bethel,BET,"Bethel, AK",Alaska,30,36,24,9,16.46
7,0.15,1/3/2016,1,3,2016,Bettles,BTT,"Bettles, AK",Alaska,22,32,9,2,3.10
8,0.60,1/3/2016,1,3,2016,Cold Bay,CDB,"Cold Bay, AK",Alaska,34,36,31,20,9.10
9,2.15,1/3/2016,1,3,2016,Cordova,CDV,"Cordova, AK",Alaska,38,43,33,9,9.76
10,0.00,1/3/2016,1,3,2016,Delta Junction/Ft Greely,BIG,"Delta Junction/Ft Greely, AK",Alaska,31,39,23,14,17.90
11,0.00,1/3/2016,1,3,2016,Fairbanks,FAI,"Fairbanks, AK",Alaska,14,30,4,2,2.20
12,0.02,1/3/2016,1,3,2016,Gulkana,GKN,"Gulkana, AK",Alaska,27,34,19,14,8.23
13,1.22,1/3/2016,1,3,2016,Homer,HOM,"Homer, AK",Alaska,39,42,35,9,11.26
14,0.00,1/3/2016,1,3,2016,Iliamna,ILI,"Iliamna, AK",Alaska,40,42,37,9,19.76
15,0.70,1/3/2016,1,3,2016,Juneau,JNU,"Juneau, AK",Alaska,36,40,31,10,9.23
16,0.14,1/3/2016,1,3,2016,Kenai,ENA,"Kenai, AK",Alaska,34,37,30,6,11.20
17,0.17,1/3/2016,1,3,2016,Ketchikan,KTN,"Ketchikan, AK",Alaska,37,41,33,15,6.16
18,0.05,1/3/2016,1,3,2016,King Salmon,AKN,"King Salmon, AK",Alaska,39,42,35,10,18.83
19,1.30,1/3/2016,1,3,2016,Kodiak,ADQ,"Kodiak, AK",Alaska,40,42,36,11,21.80
20,0.10,1/3/2016,1,3,2016,Kotzebue,OTZ,"Kotzebue, AK",Alaska,27,33,20,11,11.76
21,0.01,1/3/2016,1,3,2016,Mc Grath,MCG,"Mc Grath, AK",Alaska,30,39,20,15,3.70
22,0.08,1/3/2016,1,3,2016,Nome,OME,"Nome, AK",Alaska,29,32,25,6,12.86
23,0.00,1/3/2016,1,3,2016,Northway,ORT,"Northway, AK",Alaska,0,8,-9,20,0.36
24,0.40,1/3/2016,1,3,2016,Palmer,PAQ,"Palmer, AK",Alaska,37,42,32,8,10.50
25,0.00,1/3/2016,1,3,2016,Petersburg,PSG,"Petersburg, AK",Alaska,60,60,60,18,1.83
26,0.00,1/3/2016,1,3,2016,Puntilla Lake,PTI,"Puntilla Lake, AK",Alaska,60,60,60,0,0.00
27,0.00,1/3/2016,1,3,2016,Shemya,SYA,"Shemya, AK",Alaska,60,60,60,0,0.00
28,0.37,1/3/2016,1,3,2016,Sitka,SIT,"Sitka, AK",Alaska,43,46,39,19,11.26
29,0.55,1/3/2016,1,3,2016,Skagway,SGY,"Skagway, AK",Alaska,38,42,33,14,5.20
30,0.15,1/3/2016,1,3,2016,St Paul Island,SNP,"St Paul Island, AK",Alaska,32,35,29,22,9.03
31,0.04,1/3/2016,1,3,2016,Talkeetna,TKA,"Talkeetna, AK",Alaska,32,39,23,2,4.93
32,0.00,1/3/2016,1,3,2016,Tanana,TAL,"Tanana, AK",Alaska,21,29,13,8,3.83
33,0.05,1/3/2016,1,3,2016,Utqiagvik (Barrow),BRW,"Utqiagvik (Barrow), AK",Alaska,6,9,2,6,13.76
34,2.42,1/3/2016,1,3,2016,Yakutat,YAK,"Yakutat, AK",Alaska,36,40,32,11,5.93
35,0.00,1/3/2016,1,3,2016,Douglas Bisbee,DUG,"Douglas Bisbee, AZ",Arizona,41,57,24,6,4.20
36,0.00,1/3/2016,1,3,2016,Kingman,IGM,"Kingman, AZ",Arizona,40,54,25,4,4.20
37,0.00,1/3/2016,1,3,2016,Phoenix,PHX,"Phoenix, AZ",Arizona,58,69,45,13,5.80
38,0.00,1/3/2016,1,3,2016,Tucson,TUS,"Tucson, AZ",Arizona,56,69,43,12,12.93
39,0.00,1/3/2016,1,3,2016,Winslow,INW,"Winslow, AZ",Arizona,29,42,15,27,2.70
40,0.00,1/3/2016,1,3,2016,Fort Smith,FSM,"Fort Smith, AR",Arkansas,39,51,27,27,5.16
41,0.00,1/3/2016,1,3,2016,Harrison,HRO,"Harrison, AR",Arkansas,38,48,27,29,7.40
42,0.00,1/3/2016,1,3,2016,North Little Rock,LZK,"North Little Rock, AR",Arkansas,42,49,34,0,0.00
43,0.00,1/3/2016,1,3,2016,Bakersfield,BFL,"Bakersfield, CA",California,47,60,33,34,2.20
44,0.00,1/3/2016,1,3,2016,Bishop,BIH,"Bishop, CA",California,27,42,12,32,3.06
45,0.00,1/3/2016,1,3,2016,China Lake,NID,"China Lake, CA",California,35,49,21,21,1.56
46,0.00,1/3/2016,1,3,2016,Concord,CCR,"Concord, CA",California,44,51,37,6,4.06
47,0.06,1/3/2016,1,3,2016,Eureka,EKA,"Eureka, CA",California,44,53,33,0,0.00
48,0.00,1/3/2016,1,3,2016,Fresno,FAT,"Fresno, CA",California,46,55,36,25,0.86
49,0.00,1/3/2016,1,3,2016,Hayward,HWD,"Hayward, CA",California,47,53,41,6,6.56

In [54]:
data.Temperature_Min.mean()

45.642716359075436

# Q.7)What is the standard deviation of "precipitation" variation?

In [56]:
data.Precipitation.std()

0.988057158956622

# Q.8) Find top 20 and bottom 15  instances where "california" was state?

In [58]:
#value_counts()
data['State'].value_counts()

Alaska            1719
Texas             1272
California         999
Florida            636
Montana            583
Michigan           477
Nebraska           424
New York           424
Oregon             424
Tennessee          420
Pennsylvania       371
Mississippi        371
Ohio               371
North Carolina     371
Washington         371
Missouri           371
Georgia            318
Illinois           318
Kansas             318
Nevada             318
Colorado           318
Virginia           318
South Dakota       265
North Dakota       265
Wyoming            265
Minnesota          265
Arizona            265
Hawaii             265
Kentucky           265
Iowa               265
Louisiana          261
Oklahoma           212
Wisconsin          212
West Virginia      212
South Carolina     212
Alabama            212
Indiana            212
Idaho              159
New Mexico         159
Maine              159
Arkansas           159
Massachusetts      153
Maryland           106
Connecticut        106
New Jersey         106
New Hampshire      100
DE                  53
Utah                53
VA                  53
Vermont             53
Delaware            53
Rhode Island        53
Puerto Rico         53
Name: State, dtype: int64

In [69]:
#filtering
data[data['State']=='California'].head(20)

,Precipitation,Date,Month,Week,Year,City,Code,Station_Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
43,0.00,1/3/2016,1,3,2016,Bakersfield,BFL,"Bakersfield, CA",California,47,60,33,34,2.20
44,0.00,1/3/2016,1,3,2016,Bishop,BIH,"Bishop, CA",California,27,42,12,32,3.06
45,0.00,1/3/2016,1,3,2016,China Lake,NID,"China Lake, CA",California,35,49,21,21,1.56
46,0.00,1/3/2016,1,3,2016,Concord,CCR,"Concord, CA",California,44,51,37,6,4.06
47,0.06,1/3/2016,1,3,2016,Eureka,EKA,"Eureka, CA",California,44,53,33,0,0.00
48,0.00,1/3/2016,1,3,2016,Fresno,FAT,"Fresno, CA",California,46,55,36,25,0.86
49,0.00,1/3/2016,1,3,2016,Hayward,HWD,"Hayward, CA",California,47,53,41,6,6.56
50,0.00,1/3/2016,1,3,2016,Long Beach,LGB,"Long Beach, CA",California,54,65,43,24,2.13
51,0.00,1/3/2016,1,3,2016,Los Angeles,LAX,"Los Angeles, CA",California,55,63,45,15,2.76
52,0.00,1/3/2016,1,3,2016,Red Bluff,RBL,"Red Bluff, CA",California,44,50,36,33,7.73
53,0.00,1/3/2016,1,3,2016,Redding,RDD,"Redding, CA",California,45,51,38,34,6.16
54,0.00,1/3/2016,1,3,2016,Sacramento,SAC,"Sacramento, CA",California,44,52,34,34,3.63
55,0.00,1/3/2016,1,3,2016,Salinas,SNS,"Salinas, CA",California,49,57,41,8,6.46
56,0.00,1/3/2016,1,3,2016,San Diego,SAN,"San Diego, CA",California,55,64,45,24,1.83
57,0.04,1/3/2016,1,3,2016,San Francisco,SFO,"San Francisco, CA",California,46,51,41,10,4.43
58,0.00,1/3/2016,1,3,2016,Sandberg,SDB,"Sandberg, CA",California,39,44,33,8,18.80
59,0.00,1/3/2016,1,3,2016,Santa Barbara,SBA,"Santa Barbara, CA",California,51,62,39,12,4.90
60,0.00,1/3/2016,1,3,2016,Santa Maria,SMX,"Santa Maria, CA",California,51,63,37,21,3.86
61,0.00,1/3/2016,1,3,2016,Stockton,SCK,"Stockton, CA",California,42,51,33,26,1.86
358,0.69,1/10/2016,1,10,2016,Bakersfield,BFL,"Bakersfield, CA",California,51,58,43,13,1.75

In [73]:
data[data['State']=='California'].tail(15)

,Precipitation,Date,Month,Week,Year,City,Code,Station_Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
16475,0.02,1/1/2017,1,1,2017,Eureka,EKA,"Eureka, CA",California,44,52,35,0,0.00
16476,0.09,1/1/2017,1,1,2017,Fresno,FAT,"Fresno, CA",California,44,53,34,24,1.83
16477,0.00,1/1/2017,1,1,2017,Hayward,HWD,"Hayward, CA",California,48,58,38,10,3.18
16478,0.50,1/1/2017,1,1,2017,Long Beach,LGB,"Long Beach, CA",California,59,69,48,25,4.00
16479,0.27,1/1/2017,1,1,2017,Los Angeles,LAX,"Los Angeles, CA",California,60,69,50,10,5.21
16480,0.00,1/1/2017,1,1,2017,Red Bluff,RBL,"Red Bluff, CA",California,45,59,32,33,4.36
16481,0.00,1/1/2017,1,1,2017,Redding,RDD,"Redding, CA",California,44,59,29,32,2.53
16482,0.01,1/1/2017,1,1,2017,Sacramento,SAC,"Sacramento, CA",California,43,54,32,21,2.53
16483,0.00,1/1/2017,1,1,2017,Salinas,SNS,"Salinas, CA",California,51,61,40,11,5.40
16484,1.19,1/1/2017,1,1,2017,San Diego,SAN,"San Diego, CA",California,59,68,49,29,1.98
16485,0.00,1/1/2017,1,1,2017,San Francisco,SFO,"San Francisco, CA",California,48,55,41,14,2.98
16486,0.92,1/1/2017,1,1,2017,Sandberg,SDB,"Sandberg, CA",California,43,49,36,8,15.46
16487,0.20,1/1/2017,1,1,2017,Santa Barbara,SBA,"Santa Barbara, CA",California,52,63,40,21,1.53
16488,0.03,1/1/2017,1,1,2017,Santa Maria,SMX,"Santa Maria, CA",California,51,65,38,18,1.41
16489,0.09,1/1/2017,1,1,2017,Stockton,SCK,"Stockton, CA",California,43,55,30,20,1.98

# Q.9) Find all intances when 'wind speed is above 24' and average Temperature is 44.?

In [74]:
data.head(5)

,Precipitation,Date,Month,Week,Year,City,Code,Station_Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
0,0.00,1/3/2016,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.00,1/3/2016,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86
2,0.16,1/3/2016,1,3,2016,Mobile,MOB,"Mobile, AL",Alabama,46,51,41,35,9.73
3,0.00,1/3/2016,1,3,2016,Montgomery,MGM,"Montgomery, AL",Alabama,45,52,38,32,6.86
4,0.01,1/3/2016,1,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,34,38,29,19,7.80

In [78]:
data[(data['Wind_Speed']>8) & (data['Temperature_Avg'] ==44)]

,Precipitation,Date,Month,Week,Year,City,Code,Station_Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
605,0.11,1/10/2016,1,10,2016,Norfolk,ORF,"Norfolk, VA",Virginia,44,50,38,10,11.30
658,1.66,1/17/2016,1,17,2016,Sitka,SIT,"Sitka, AK",Alaska,44,47,41,11,12.07
1224,0.00,1/24/2016,1,24,2016,Lubbock,LBB,"Lubbock, TX",Texas,44,61,28,26,9.82
1382,0.04,1/31/2016,1,31,2016,Louisville,SDF,"Louisville, KY",Kentucky,44,54,33,23,8.28
1422,0.00,1/31/2016,1,31,2016,Springfield,SGF,"Springfield, MO",Missouri,44,59,29,23,8.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15228,0.04,12/4/2016,12,4,2016,Bridgeport,BDR,"Bridgeport, CT",Connecticut,44,51,37,29,8.95
15402,0.17,12/4/2016,12,4,2016,Williamsport,IPT,"Williamsport, PA",Pennsylvania,44,49,39,29,9.27
15459,0.63,12/4/2016,12,4,2016,Seattle,SEA,"Seattle, WA",Washington,44,47,40,18,8.97
15750,0.15,12/11/2016,12,11,2016,Dallas-Fort Worth,DFW,"Dallas-Fort Worth, TX",Texas,44,51,36,12,8.42
16067,0.00,12/18/2016,12,18,2016,Dallas-Fort Worth,DFW,"Dallas-Fort Worth, TX",Texas,44,54,33,18,9.84

# Q.10) What is the mean value of each column against each 'State'?

In [79]:
data.head(4)

,Precipitation,Date,Month,Week,Year,City,Code,Station_Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
0,0.00,1/3/2016,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.00,1/3/2016,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86
2,0.16,1/3/2016,1,3,2016,Mobile,MOB,"Mobile, AL",Alabama,46,51,41,35,9.73
3,0.00,1/3/2016,1,3,2016,Montgomery,MGM,"Montgomery, AL",Alabama,45,52,38,32,6.86

In [80]:
#groupby function
data.groupby('State').mean()

,Precipitation,Month,Week,Year,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
State,,,,,,,,,
Alabama,0.776179,6.339623,15.660377,2016.018868,66.528302,77.226415,55.292453,19.202830,4.817736
Alaska,0.566126,6.392670,15.603839,2016.019779,41.157650,47.085515,34.773124,15.506690,6.429959
Arizona,0.162566,6.339623,15.660377,2016.018868,66.286792,81.007547,51.064151,18.271698,4.662075
Arkansas,0.603711,6.339623,15.660377,2016.018868,62.308176,72.345912,51.779874,11.647799,3.298113
California,0.323774,6.308308,15.666667,2016.018018,62.363363,73.029029,51.240240,22.421421,4.893634
Colorado,0.182987,6.339623,15.660377,2016.018868,49.273585,64.591195,33.553459,18.201258,4.322830
Connecticut,0.587830,6.339623,15.660377,2016.018868,53.396226,62.367925,43.811321,20.971698,6.474906
DE,0.632453,6.339623,15.660377,2016.018868,56.056604,65.264151,46.452830,20.773585,6.760377
Delaware,0.632453,6.339623,15.660377,2016.018868,56.056604,65.264151,46.452830,20.773585,6.760377
Florida,0.891006,6.339623,15.660377,2016.018868,73.926101,82.215409,65.166667,15.718553,6.299953
Georgia,0.712799,6.339623,15.660377,2016.018868,66.220126,77.437107,54.496855,19.330189,4.682516
Hawaii,0.664868,6.339623,15.660377,2016.018868,76.384906,82.954717,69.366038,10.347170,8.971585
Idaho,0.238113,6.339623,15.660377,2016.018868,51.698113,63.352201,39.672956,19.018868,4.822453
Illinois,0.609182,6.339623,15.660377,2016.018868,53.377358,62.270440,43.933962,19.591195,7.081761
Indiana,0.790142,6.339623,15.660377,2016.018868,53.976415,63.165094,44.301887,20.165094,6.836934
Iowa,0.659208,6.339623,15.660377,2016.018868,50.796226,60.162264,40.920755,19.860377,8.008679
Kansas,0.547673,6.339623,15.660377,2016.018868,56.867925,69.201258,43.987421,18.981132,8.249497
Kentucky,0.777660,6.339623,15.660377,2016.018868,58.286792,67.856604,48.222642,19.901887,5.003283
Louisiana,1.252452,6.329502,15.586207,2016.019157,69.475096,78.927203,59.540230,15.206897,5.115709
Maine,0.681698,6.339623,15.660377,2016.018868,45.415094,55.075472,35.251572,21.823899,5.913648
Maryland,0.697170,6.339623,15.660377,2016.018868,56.971698,66.462264,46.820755,19.650943,5.627547
Massachusetts,0.462222,6.294118,15.549020,2016.019608,53.261438,59.202614,47.111111,20.300654,8.746993
Michigan,0.587925,6.339623,15.660377,2016.018868,48.002096,56.867925,38.647799,17.911950,5.966897
Minnesota,0.599811,6.339623,15.660377,2016.018868,44.675472,53.724528,35.203774,19.894340,7.512604
Mississippi,0.885202,6.339623,15.660377,2016.018868,66.474394,77.336927,55.159030,18.415094,4.747062
Missouri,0.712318,6.339623,15.660377,2016.018868,57.423181,67.331536,46.943396,19.431267,7.061024
Montana,0.254768,6.339623,15.660377,2016.018868,45.627787,57.855918,32.962264,21.180103,6.455180
Nebraska,0.403986,6.339623,15.660377,2016.018868,51.634434,64.386792,38.429245,20.780660,8.054528
Nevada,0.133208,6.339623,15.660377,2016.018868,55.628931,69.877358,40.613208,18.522013,5.224465
New Hampshire,0.479000,6.450000,15.430000,2016.020000,51.110000,57.810000,44.050000,23.310000,18.017900
New Jersey,0.659717,6.339623,15.660377,2016.018868,56.066038,64.915094,46.584906,19.952830,7.191604
New Mexico,0.223019,6.339623,15.660377,2016.018868,58.622642,72.672956,44.157233,19.962264,6.353585
New York,0.597689,6.339623,15.660377,2016.018868,51.040094,59.771226,41.823113,20.518868,6.929929
North Carolina,0.794528,6.339623,15.660377,2016.018868,61.770889,71.404313,51.676550,19.668464,5.236954
North Dakota,0.341887,6.339623,15.660377,2016.018868,45.166038,56.449057,33.486792,20.833962,8.457208
Ohio,0.612372,6.339623,15.660377,2016.018868,52.665768,61.830189,43.008086,20.113208,7.212156
Oklahoma,0.442311,6.339623,15.660377,2016.018868,61.716981,73.580189,49.320755,18.014151,8.456792
Oregon,0.627217,6.339623,15.660377,2016.018868,52.870283,63.971698,41.254717,21.308962,4.863160
Pennsylvania,0.594771,6.339623,15.660377,2016.018868,53.919137,62.792453,44.021563,21.024259,5.855526
Puerto Rico,1.238113,6.339623,15.660377,2016.018868,81.358491,86.566038,75.622642,9.056604,6.718868
Rhode Island,0.661887,6.339623,15.660377,2016.018868,53.037736,62.000000,43.622642,20.471698,7.056981
South Carolina,0.687500,6.339623,15.660377,2016.018868,65.188679,75.863208,54.047170,17.952830,4.973208
South Dakota,0.344604,6.339623,15.660377,2016.018868,48.415094,60.324528,36.079245,21.060377,8.469660
Tennessee,0.742476,6.333333,15.614286,2016.019048,60.802381,71.328571,49.776190,19.592857,4.082381
Texas,0.621973,6.339623,15.660377,2016.018868,68.181604,78.849057,57.015723,15.917453,7.726423
Utah,0.247925,6.339623,15.660377,2016.018868,55.698113,66.094340,44.792453,20.622642,4.626792
VA,0.760566,6.339623,15.660377,2016.018868,58.283019,68.018868,48.132075,20.566038,5.078113
Vermont,0.481321,6.339623,15.660377,2016.018868,48.773585,57.622642,39.452830,23.056604,6.174151
Virginia,0.810283,6.339623,15.660377,2016.018868,58.974843,67.946541,49.553459,18.729560,5.883648
Washington,0.758356,6.339623,15.660377,2016.018868,51.366577,61.212938,41.070081,19.229111,4.930782
West Virginia,0.738019,6.339623,15.660377,2016.018868,55.023585,65.311321,44.235849,21.533019,4.146698
Wisconsin,0.638491,6.339623,15.660377,2016.018868,49.165094,57.575472,40.231132,19.485849,6.741368
Wyoming,0.226491,6.339623,15.660377,2016.018868,46.490566,60.018868,32.509434,23.377358,7.461283

# Q.11) What is the minimum & maximum value of each column against each 'State'?

In [82]:
data.head(2)

,Precipitation,Date,Month,Week,Year,City,Code,Station_Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
0,0.0,1/3/2016,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.0,1/3/2016,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86

In [85]:
#group by min values of each state
(data.groupby('State').min())

,Precipitation,Date,Month,Week,Year,City,Code,Station_Location,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
State,,,,,,,,,,,,,
Alabama,0.00,1/1/2017,1,1,2016,Birmingham,BHM,"Birmingham, AL",33,40,25,6,0.91
Alaska,0.00,1/1/2017,1,1,2016,Anchorage,ADQ,"Anchorage, AK",-27,-19,-35,0,0.00
Arizona,0.00,1/1/2017,1,1,2016,Douglas Bisbee,DUG,"Douglas Bisbee, AZ",29,42,15,4,1.30
Arkansas,0.00,1/1/2017,1,1,2016,Fort Smith,FSM,"Fort Smith, AR",28,34,21,0,0.00
California,0.00,1/1/2017,1,1,2016,Bakersfield,BFL,"Bakersfield, CA",27,42,12,0,0.00
Colorado,0.00,1/1/2017,1,1,2016,Alamosa,ALS,"Alamosa, CO",-10,3,-23,3,0.40
Connecticut,0.00,1/1/2017,1,1,2016,Bridgeport,BDL,"Bridgeport, CT",16,25,7,4,3.28
DE,0.00,1/1/2017,1,1,2016,Newark,NWK,"Newark, DE",24,29,18,5,3.21
Delaware,0.00,1/1/2017,1,1,2016,Wilmington,ILG,"Wilmington, DE",24,29,18,5,3.21
Florida,0.00,1/1/2017,1,1,2016,Daytona Beach,DAB,"Daytona Beach, FL",44,52,32,1,0.80
Georgia,0.00,1/1/2017,1,1,2016,Alma,AGS,"Alma, GA",35,43,25,5,0.30
Hawaii,0.00,1/1/2017,1,1,2016,Hilo,HNL,"Hilo, HI",60,60,58,2,1.30
Idaho,0.00,1/1/2017,1,1,2016,Boise,BOI,"Boise, ID",8,21,-4,2,1.20
Illinois,0.00,1/1/2017,1,1,2016,Chicago,MLI,"Chicago, IL",9,17,0,3,1.65
Indiana,0.00,1/1/2017,1,1,2016,Evansville,EVV,"Evansville, IN",13,21,4,0,0.00
Iowa,0.00,1/1/2017,1,1,2016,Cedar Rapids,ALO,"Cedar Rapids, IA",4,12,-3,1,2.40
Kansas,0.00,1/1/2017,1,1,2016,Concordia,CNK,"Concordia, KS",15,26,2,5,2.05
Kentucky,0.00,1/1/2017,1,1,2016,Covington,CVG,"Covington, KY",18,24,12,5,0.18
Louisiana,0.00,1/1/2017,1,1,2016,Baton Rouge,ASD,"Baton Rouge, LA",43,52,33,2,0.94
Maine,0.00,1/1/2017,1,1,2016,Bangor,BGR,"Bangor, ME",6,14,-2,8,0.30
Maryland,0.00,1/1/2017,1,1,2016,Baltimore,BWI,"Baltimore, MD",23,30,16,2,2.50
Massachusetts,0.00,1/1/2017,1,1,2016,Boston,BOS,"Boston, MA",13,22,3,0,0.00
Michigan,0.00,1/1/2017,1,1,2016,Alpena,ANJ,"Alpena, MI",5,12,-2,0,0.00
Minnesota,0.00,1/1/2017,1,1,2016,Duluth,DLH,"Duluth, MN",-7,0,-17,2,1.80
Mississippi,0.00,1/1/2017,1,1,2016,Greenville,GLH,"Greenville, MS",34,41,26,4,0.65
Missouri,0.00,1/1/2017,1,1,2016,Cape Girardeau,CGI,"Cape Girardeau, MO",16,25,7,5,1.02
Montana,0.00,1/1/2017,1,1,2016,Billings,BIL,"Billings, MT",-3,3,-14,2,0.50
Nebraska,0.00,1/1/2017,1,1,2016,Grand Island,BFF,"Grand Island, NE",4,18,-11,1,2.62
Nevada,0.00,1/1/2017,1,1,2016,Ely,DRA,"Ely, NV",7,22,-8,3,0.60
New Hampshire,0.00,1/1/2017,1,1,2016,Concord,CON,"Concord, NH",2,12,-12,2,1.58
New Jersey,0.00,1/1/2017,1,1,2016,Atlantic City,ACY,"Atlantic City, NJ",25,31,18,2,3.75
New Mexico,0.00,1/1/2017,1,1,2016,Albuquerque,ABQ,"Albuquerque, NM",27,36,15,1,1.67
New York,0.00,1/1/2017,1,1,2016,Albany,ALB,"Albany, NY",14,21,5,4,1.80
North Carolina,0.00,1/1/2017,1,1,2016,Asheville,AVL,"Asheville, NC",27,34,19,3,1.00
North Dakota,0.00,1/1/2017,1,1,2016,Bismarck,BIS,"Bismarck, ND",-6,3,-16,2,1.40
Ohio,0.00,1/1/2017,1,1,2016,Akron,CAK,"Akron, OH",15,22,7,2,1.40
Oklahoma,0.00,1/1/2017,1,1,2016,Gage,GAG,"Gage, OK",26,38,12,4,1.80
Oregon,0.00,1/1/2017,1,1,2016,Astoria,AST,"Astoria, OR",7,20,-6,1,0.40
Pennsylvania,0.00,1/1/2017,1,1,2016,Allentown,ABE,"Allentown, PA",15,21,7,4,0.50
Puerto Rico,0.04,1/1/2017,1,1,2016,San Juan,SJU,"San Juan, PR",77,82,71,7,2.04
Rhode Island,0.00,1/1/2017,1,1,2016,Providence,PVD,"Providence, RI",18,27,9,1,3.40
South Carolina,0.00,1/1/2017,1,1,2016,Anderson,AND,"Anderson, SC",32,40,23,2,0.60
South Dakota,0.00,1/1/2017,1,1,2016,Aberdeen,ABR,"Aberdeen, SD",-6,7,-20,2,2.82
Tennessee,0.00,1/1/2017,1,1,2016,Bristol/Jhnsn Cty/Kngsprt,BNA,"Bristol/Jhnsn Cty/Kngsprt, TN",24,30,16,3,0.40
Texas,0.00,1/1/2017,1,1,2016,Abilene,ABI,"Abilene, TX",32,41,14,1,0.55
Utah,0.00,1/1/2017,1,1,2016,Salt Lake City,SLC,"Salt Lake City, UT",15,24,7,8,1.28
VA,0.00,1/1/2017,1,1,2016,Blacksburg,BCB,"Blacksburg, VA",24,31,17,8,1.25
Vermont,0.00,1/1/2017,1,1,2016,Burlington,BTV,"Burlington, VT",14,23,5,14,3.10
Virginia,0.00,1/1/2017,1,1,2016,Lynchburg,DCA,"Lynchburg, VA",24,31,15,3,1.04
Washington,0.00,1/1/2017,1,1,2016,Deer Park,DEW,"Deer Park, WA",8,19,-3,1,0.50
West Virginia,0.00,1/1/2017,1,1,2016,Beckley,BKW,"Beckley, WV",12,21,2,3,0.83
Wisconsin,0.00,1/1/2017,1,1,2016,Green Bay,GRB,"Green Bay, WI",6,12,0,2,2.23
Wyoming,0.00,1/1/2017,1,1,2016,Casper,CPR,"Casper, WY",3,17,-13,5,0.43

In [87]:
#group by the maximum values of each state
data.groupby('State').max()

,Precipitation,Date,Month,Week,Year,City,Code,Station_Location,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
State,,,,,,,,,,,,,
Alabama,4.44,9/4/2016,12,31,2017,Montgomery,MOB,"Montgomery, AL",86,99,77,35,12.80
Alaska,10.34,9/4/2016,12,31,2017,Yakutat,YAK,"Yakutat, AK",69,79,60,36,27.58
Arizona,2.28,9/4/2016,12,31,2017,Winslow,TUS,"Winslow, AZ",99,110,88,31,12.93
Arkansas,6.08,9/4/2016,12,31,2017,North Little Rock,LZK,"North Little Rock, AR",88,99,77,31,9.21
California,6.60,9/4/2016,12,31,2017,Stockton,SNS,"Stockton, CA",93,111,77,36,18.80
Colorado,1.82,9/4/2016,12,31,2017,Pueblo,PUB,"Pueblo, CO",84,101,67,35,13.30
Connecticut,2.81,9/4/2016,12,31,2017,Windsor Locks,BDR,"Windsor Locks, CT",82,92,73,36,13.46
DE,3.27,9/4/2016,12,31,2017,Newark,NWK,"Newark, DE",83,91,75,30,14.62
Delaware,3.27,9/4/2016,12,31,2017,Wilmington,ILG,"Wilmington, DE",83,91,75,30,14.62
Florida,15.19,9/4/2016,12,31,2017,West Palm Beach,VRB,"West Palm Beach, FL",87,98,83,35,15.58
Georgia,11.52,9/4/2016,12,31,2017,Savannah,SAV,"Savannah, GA",87,99,76,32,13.25
Hawaii,14.03,9/4/2016,12,31,2017,Lihue,OGG,"Lihue, HI",83,90,77,31,19.22
Idaho,1.74,9/4/2016,12,31,2017,Pocatello,PIH,"Pocatello, ID",82,98,65,34,12.51
Illinois,5.59,9/4/2016,12,31,2017,Springfield,UIN,"Springfield, IL",82,92,73,35,14.43
Indiana,12.65,9/4/2016,12,31,2017,South Bend,SBN,"South Bend, IN",83,94,73,29,15.03
Iowa,5.62,9/4/2016,12,31,2017,Waterloo,SUX,"Waterloo, IA",83,92,74,36,14.33
Kansas,8.96,9/4/2016,12,31,2017,Wichita,TOP,"Wichita, KS",88,101,76,35,16.20
Kentucky,6.06,9/4/2016,12,31,2017,Paducah,SDF,"Paducah, KY",84,93,75,31,11.80
Louisiana,20.89,9/4/2016,12,31,2017,Slidell,SHV,"Slidell, LA",89,99,81,36,12.64
Maine,4.28,9/4/2016,12,31,2017,Portland,PWM,"Portland, ME",77,89,65,31,10.41
Maryland,3.38,9/4/2016,12,31,2017,Salisbury,SBY,"Salisbury, MD",84,93,73,31,11.01
Massachusetts,4.29,9/4/2016,12,31,2017,Worcester,ORH,"Worcester, MA",80,91,71,30,15.84
Michigan,4.49,9/4/2016,12,31,2017,Sault Ste Marie,MQT,"Sault Ste Marie, MI",80,92,70,30,13.33
Minnesota,4.43,9/4/2016,12,31,2017,St Cloud,STC,"St Cloud, MN",80,89,70,32,14.41
Mississippi,13.36,9/4/2016,12,31,2017,Tupelo,TUP,"Tupelo, MS",87,99,79,35,13.17
Missouri,6.67,9/4/2016,12,31,2017,St Louis,VIH,"St Louis, MO",86,95,76,33,13.66
Montana,3.49,9/4/2016,12,31,2017,Missoula,MSO,"Missoula, MT",81,97,65,33,21.86
Nebraska,4.19,9/4/2016,12,31,2017,Valentine,VTN,"Valentine, NE",83,97,76,36,15.64
Nevada,1.53,9/4/2016,12,31,2017,Winnemucca,WMC,"Winnemucca, NV",100,111,88,36,16.47
New Hampshire,3.79,9/4/2016,12,31,2017,Mt. Washington,MWN,"Mt. Washington, NH",77,91,62,31,61.10
New Jersey,4.85,9/4/2016,12,31,2017,Newark,EWR,"Newark, NJ",84,93,75,30,14.11
New Mexico,4.05,9/4/2016,12,31,2017,Roswell,ROW,"Roswell, NM",88,106,71,35,25.80
New York,4.93,9/4/2016,12,31,2017,Syracuse,SYR,"Syracuse, NY",86,93,77,32,15.71
North Carolina,7.87,9/4/2016,12,31,2017,Wilmington,RDU,"Wilmington, NC",87,96,79,34,13.12
North Dakota,3.14,9/4/2016,12,31,2017,Williston,ISN,"Williston, ND",77,91,64,36,17.50
Ohio,5.05,9/4/2016,12,31,2017,Youngstown/Warren,YNG,"Youngstown/Warren, OH",81,89,72,31,15.76
Oklahoma,4.92,9/4/2016,12,31,2017,Tulsa,TUL,"Tulsa, OK",89,99,79,34,16.08
Oregon,8.06,9/4/2016,12,31,2017,Salem,SLE,"Salem, OR",83,102,63,36,19.93
Pennsylvania,5.06,9/4/2016,12,31,2017,Williamsport,PIT,"Williamsport, PA",85,93,76,30,14.46
Puerto Rico,7.61,9/4/2016,12,31,2017,San Juan,SJU,"San Juan, PR",85,91,79,15,11.95
Rhode Island,2.15,9/4/2016,12,31,2017,Providence,PVD,"Providence, RI",79,89,69,29,13.80
South Carolina,10.49,9/4/2016,12,31,2017,Greer,GSP,"Greer, SC",89,101,79,30,12.20
South Dakota,3.61,9/4/2016,12,31,2017,Sioux Falls,RAP,"Sioux Falls, SD",83,97,71,36,16.87
Tennessee,10.58,9/4/2016,12,31,2017,Oak Ridge,TYS,"Oak Ridge, TN",87,97,79,35,9.72
Texas,9.28,9/4/2016,12,31,2017,Wichita Falls,VCT,"Wichita Falls, TX",92,104,82,36,20.30
Utah,1.61,9/4/2016,12,31,2017,Salt Lake City,SLC,"Salt Lake City, UT",88,101,74,32,11.15
VA,4.30,9/4/2016,12,31,2017,Blacksburg,BCB,"Blacksburg, VA",82,93,71,29,12.16
Vermont,2.09,9/4/2016,12,31,2017,Burlington,BTV,"Burlington, VT",77,87,66,32,9.86
Virginia,9.91,9/4/2016,12,31,2017,Washington,WAL,"Washington, VA",86,95,77,35,15.72
Washington,8.21,9/4/2016,12,31,2017,Yakima,YKM,"Yakima, WA",83,99,67,34,11.40
West Virginia,3.50,9/4/2016,12,31,2017,Huntington,HTS,"Huntington, WV",81,91,72,33,12.13
Wisconsin,4.70,9/4/2016,12,31,2017,Milwaukee,MSN,"Milwaukee, WI",80,89,70,29,14.70
Wyoming,4.45,9/4/2016,12,31,2017,Sheridan,SHR,"Sheridan, WY",77,96,60,36,20.75

# Q.12) Find all the records where state is maine?

In [90]:
data[data['State']== 'Maine']

,Precipitation,Date,Month,Week,Year,City,Code,Station_Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
129,0.00,1/3/2016,1,3,2016,Bangor,BGR,"Bangor, ME",Maine,29,35,22,24,4.60
130,0.10,1/3/2016,1,3,2016,Caribou,CAR,"Caribou, ME",Maine,23,29,17,25,5.66
131,0.01,1/3/2016,1,3,2016,Portland,PWM,"Portland, ME",Maine,34,39,28,24,7.53
444,1.99,1/10/2016,1,10,2016,Bangor,BGR,"Bangor, ME",Maine,22,34,9,21,5.52
445,0.52,1/10/2016,1,10,2016,Caribou,CAR,"Caribou, ME",Maine,18,26,9,19,6.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16241,0.10,12/25/2016,12,25,2016,Caribou,CAR,"Caribou, ME",Maine,18,28,8,23,6.20
16242,0.22,12/25/2016,12,25,2016,Portland,PWM,"Portland, ME",Maine,27,36,19,26,6.22
16557,1.73,1/1/2017,1,1,2017,Bangor,BGR,"Bangor, ME",Maine,27,36,17,24,4.36
16558,1.89,1/1/2017,1,1,2017,Caribou,CAR,"Caribou, ME",Maine,20,28,11,21,5.71
16559,2.10,1/1/2017,1,1,2017,Portland,PWM,"Portland, ME",Maine,31,40,21,29,6.36

# Q.13) Find all instances when 'State is VA' or 'wind speed' is above 44?

In [120]:
#data[(data['State']=='VA') | (data['Wind_Speed']> 44 )].tail(20)
#data[(data['State']=='VA') | (data['Wind_Speed']> 44 )].head(30)
data[(data['State']=='VA') | (data['Wind_Speed']> 44 )]

,Precipitation,Date,Month,Week,Year,City,Code,Station_Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
191,0.00,1/3/2016,1,3,2016,Mt. Washington,MWN,"Mt. Washington, NH",New Hampshire,60,60,60,27,52.60
287,0.00,1/3/2016,1,3,2016,Blacksburg,BCB,"Blacksburg, VA",VA,41,49,33,28,9.33
602,0.90,1/10/2016,1,10,2016,Blacksburg,BCB,"Blacksburg, VA",VA,34,43,24,20,4.11
917,0.50,1/17/2016,1,17,2016,Blacksburg,BCB,"Blacksburg, VA",VA,35,44,26,28,8.55
1232,1.59,1/24/2016,1,24,2016,Blacksburg,BCB,"Blacksburg, VA",VA,24,31,17,28,8.92
1547,0.00,1/31/2016,1,31,2016,Blacksburg,BCB,"Blacksburg, VA",VA,36,48,24,23,3.51
1766,0.00,2/7/2016,2,7,2016,Mt. Washington,MWN,"Mt. Washington, NH",New Hampshire,60,60,60,26,45.16
1862,1.23,2/7/2016,2,7,2016,Blacksburg,BCB,"Blacksburg, VA",VA,41,49,33,21,4.52
2177,0.12,2/14/2016,2,14,2016,Blacksburg,BCB,"Blacksburg, VA",VA,25,33,18,26,8.97
2492,2.48,2/21/2016,2,21,2016,Blacksburg,BCB,"Blacksburg, VA",VA,40,48,31,24,5.65
2807,1.41,2/28/2016,2,28,2016,Blacksburg,BCB,"Blacksburg, VA",VA,44,52,36,22,8.55
3028,0.00,3/6/2016,3,6,2016,Mt. Washington,MWN,"Mt. Washington, NH",New Hampshire,60,60,60,25,61.10
3124,0.38,3/6/2016,3,6,2016,Blacksburg,BCB,"Blacksburg, VA",VA,41,53,30,25,5.36
3439,0.15,3/13/2016,3,13,2016,Blacksburg,BCB,"Blacksburg, VA",VA,62,73,51,16,3.80
3754,1.33,3/20/2016,3,20,2016,Blacksburg,BCB,"Blacksburg, VA",VA,55,65,45,20,4.02
4069,0.15,3/27/2016,3,27,2016,Blacksburg,BCB,"Blacksburg, VA",VA,55,65,44,21,6.34
4290,0.00,4/3/2016,4,3,2016,Mt. Washington,MWN,"Mt. Washington, NH",New Hampshire,60,60,60,25,50.06
4386,0.14,4/3/2016,4,3,2016,Blacksburg,BCB,"Blacksburg, VA",VA,57,69,45,27,12.16
4702,0.09,4/10/2016,4,10,2016,Blacksburg,BCB,"Blacksburg, VA",VA,47,58,35,25,10.01
5018,0.00,4/17/2016,4,17,2016,Blacksburg,BCB,"Blacksburg, VA",VA,55,68,41,16,4.54
5334,0.21,4/24/2016,4,24,2016,Blacksburg,BCB,"Blacksburg, VA",VA,64,77,50,22,4.85
5651,1.01,5/1/2016,5,1,2016,Blacksburg,BCB,"Blacksburg, VA",VA,66,78,54,12,4.40
5968,1.00,5/8/2016,5,8,2016,Blacksburg,BCB,"Blacksburg, VA",VA,62,71,52,28,5.74
6285,2.63,5/15/2016,5,15,2016,Blacksburg,BCB,"Blacksburg, VA",VA,64,73,54,19,7.00
6602,1.00,5/22/2016,5,22,2016,Blacksburg,BCB,"Blacksburg, VA",VA,58,65,51,15,2.98
6919,0.48,5/29/2016,5,29,2016,Blacksburg,BCB,"Blacksburg, VA",VA,70,81,58,14,2.57
7236,0.60,6/5/2016,6,5,2016,Blacksburg,BCB,"Blacksburg, VA",VA,75,83,66,17,2.50
7551,0.00,6/12/2016,6,12,2016,Blacksburg,BCB,"Blacksburg, VA",VA,74,86,62,29,8.11
7866,2.72,6/19/2016,6,19,2016,Blacksburg,BCB,"Blacksburg, VA",VA,72,85,60,16,3.68
8181,2.60,6/26/2016,6,26,2016,Blacksburg,BCB,"Blacksburg, VA",VA,74,83,65,20,3.92
8497,1.09,7/3/2016,7,3,2016,Blacksburg,BCB,"Blacksburg, VA",VA,74,81,65,16,3.26
8811,0.94,7/10/2016,7,10,2016,Blacksburg,BCB,"Blacksburg, VA",VA,77,85,69,25,6.30
9125,0.21,7/17/2016,7,17,2016,Blacksburg,BCB,"Blacksburg, VA",VA,78,88,67,23,2.18
9439,0.00,7/24/2016,7,24,2016,Blacksburg,BCB,"Blacksburg, VA",VA,81,93,69,20,2.68
9753,3.31,7/31/2016,7,31,2016,Blacksburg,BCB,"Blacksburg, VA",VA,82,92,71,25,2.30
10070,1.39,8/7/2016,8,7,2016,Blacksburg,BCB,"Blacksburg, VA",VA,76,82,70,13,2.41
10387,0.73,8/14/2016,8,14,2016,Blacksburg,BCB,"Blacksburg, VA",VA,78,86,70,17,3.50
10704,1.53,8/21/2016,8,21,2016,Blacksburg,BCB,"Blacksburg, VA",VA,78,86,70,20,2.40
11021,0.00,8/28/2016,8,28,2016,Blacksburg,BCB,"Blacksburg, VA",VA,77,87,66,20,2.55
11338,0.33,9/4/2016,9,4,2016,Blacksburg,BCB,"Blacksburg, VA",VA,70,79,61,12,3.27
11654,0.00,9/11/2016,9,11,2016,Blacksburg,BCB,"Blacksburg, VA",VA,78,89,66,25,3.98
11970,0.00,9/18/2016,9,18,2016,Blacksburg,BCB,"Blacksburg, VA",VA,74,84,63,16,3.11
12286,0.83,9/25/2016,9,25,2016,Blacksburg,BCB,"Blacksburg, VA",VA,74,83,63,10,4.07
12603,0.00,10/2/2016,10,2,2016,Blacksburg,BCB,"Blacksburg, VA",VA,67,76,57,18,1.25
12920,4.30,10/9/2016,10,9,2016,Blacksburg,BCB,"Blacksburg, VA",VA,63,70,56,8,5.18
13237,0.00,10/16/2016,10,16,2016,Blacksburg,BCB,"Blacksburg, VA",VA,57,69,45,13,2.42
13554,0.12,10/23/2016,10,23,2016,Blacksburg,BCB,"Blacksburg, VA",VA,65,76,54,25,7.02
13871,0.00,10/30/2016,10,30,2016,Blacksburg,BCB,"Blacksburg, VA",VA,60,73,47,21,3.87
14188,0.02,11/6/2016,11,6,2016,Blacksburg,BCB,"Blacksburg, VA",VA,60,71,48,24,4.55
14502,0.00,11/13/2016,11,13,2016,Blacksburg,BCB,"Blacksburg, VA",VA,52,64,38,20,5.62
14816,0.00,11/20/2016,11,20,2016,Blacksburg,BCB,"Blacksburg, VA",VA,50,64,35,19,6.50
15130,0.00,11/27/2016,11,27,2016,Blacksburg,BCB,"Blacksburg, VA",VA,45,56,34,26,5.65
15447,0.20,12/4/2016,12,4,2016,Blacksburg,BCB,"Blacksburg, VA",VA,43,48,38,25,9.15
15764,1.67,12/11/2016,12,11,2016,Blacksburg,BCB,"Blacksburg, VA",VA,38,45,30,20,6.08
15985,2.42,12/18/2016,12,18,2016,Mt. Washington,MWN,"Mt. Washington, NH",New Hampshire,2,16,-12,26,49.60
16081,0.18,12/18/2016,12,18,2016,Blacksburg,BCB,"Blacksburg, VA",VA,38,48,28,22,5.90
16302,0.55,12/25/2016,12,25,2016,Mt. Washington,MWN,"Mt. Washington, NH",New Hampshire,10,16,3,28,47.20
16398,0.48,12/25/2016,12,25,2016,Blacksburg,BCB,"Blacksburg, VA",VA,41,50,32,21,2.65
16619,2.71,1/1/2017,1,1,2017,Mt. Washington,MWN,"Mt. Washington, NH",New Hampshire,11,21,0,25,47.56
16715,0.26,1/1/2017,1,1,2017,Blacksburg,BCB,"Blacksburg, VA",VA,42,50,34,24,7.20

# Q.15) Find all instances 
    when:
    1.State is new york and precipitation is greater than 0.48
    or
    wind direction is above 25

In [121]:
data.head(6)

,Precipitation,Date,Month,Week,Year,City,Code,Station_Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
0,0.00,1/3/2016,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.00,1/3/2016,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86
2,0.16,1/3/2016,1,3,2016,Mobile,MOB,"Mobile, AL",Alabama,46,51,41,35,9.73
3,0.00,1/3/2016,1,3,2016,Montgomery,MGM,"Montgomery, AL",Alabama,45,52,38,32,6.86
4,0.01,1/3/2016,1,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,34,38,29,19,7.80
5,0.09,1/3/2016,1,3,2016,Annette,ANN,"Annette, AK",Alaska,38,44,31,9,8.70

In [122]:
data[(data['State'] == 'New York') & (data['Precipitation'] > 0.48) | (data['Wind_Direction'] >25)]

,Precipitation,Date,Month,Week,Year,City,Code,Station_Location,State,Temperature_Avg,Temperature_Max,Temperature_Min,Wind_Direction,Wind_Speed
0,0.00,1/3/2016,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.00,1/3/2016,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86
2,0.16,1/3/2016,1,3,2016,Mobile,MOB,"Mobile, AL",Alabama,46,51,41,35,9.73
3,0.00,1/3/2016,1,3,2016,Montgomery,MGM,"Montgomery, AL",Alabama,45,52,38,32,6.86
39,0.00,1/3/2016,1,3,2016,Winslow,INW,"Winslow, AZ",Arizona,29,42,15,27,2.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16713,0.00,1/1/2017,1,1,2017,Wichita Falls,SPS,"Wichita Falls, TX",Texas,49,61,36,26,7.20
16714,0.00,1/1/2017,1,1,2017,Salt Lake City,SLC,"Salt Lake City, UT",Utah,18,27,10,29,1.56
16729,0.01,1/1/2017,1,1,2017,Yakima,YKM,"Yakima, WA",Washington,28,40,15,27,2.41
16739,0.00,1/1/2017,1,1,2017,Cheyenne,CYS,"Cheyenne, WY",Wyoming,32,42,21,26,15.16
16740,0.00,1/1/2017,1,1,2017,Lander,LND,"Lander, WY",Wyoming,17,29,4,26,1.65